parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''
    env(DB_NAME): ''
    env(DB_HOST): ''
    env(DB_PORT): ''
    env(DB_ROOT_USER): ''
    env(DB_ROOT_PASSWORD): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        dbname: '%env(DB_NAME)%'
        host: '%env(DB_HOST)%'
        port: '%env(DB_PORT)%'
        user: '%env(DB_ROOT_USER)%'
        password: '%env(DB_ROOT_PASSWORD)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

services:
    # Doctrine Extension listeners to handle behaviors
    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
        - { name: doctrine.event_subscriber, connection: default }
        calls:
        - [ setAnnotationReader, [ "@annotation_reader" ] ]