jms_serializer:
    visitors:
        xml:
            format_output: '%kernel.debug%'
#    metadata:
#        auto_detection: true
#        directories:
#            App:
#                namespace_prefix: "App\\"
#                path: "@AppBundle"
