security:
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$12$LD21.Xr7SFlxshaqwI2.f.DTNIkKgOtB71Ik8pEikIpD5wDkD.O1O
                        roles: 'ROLE_BO_USER'

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            json_login:
                check_path: /api/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api_admin:
            pattern: ^\/api\/v\d*\/admin.*
            stateless: true
            anonymous: true
            guard:
                authenticators:
                - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
    - { path: ^\/api\/v\d*\/admin.*, roles: IS_AUTHENTICATED_FULLY, methods: [DELETE, POST, PUT, GET] }
    - { path: ^\/api\/v\d*\/((?!admin)(?!doc.json)(?!status)).*, roles: IS_AUTHENTICATED_FULLY, methods: [GET] }
